<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload7846c93acdc175fb93142731e3828608($class) {
	static $classes = null;
	if ($classes === null) {
		$classes = array(
				'ca\\mcgill\\ecse321\\tamas\\web\\authentication\\authentication' => '/authentication/Authentication.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\authentication\\courseworker' => '/authentication/CourseWorker.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\authentication\\departmentadministrator' => '/authentication/DepartmentAdministrator.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\authentication\\instructor' => '/authentication/Instructor.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\authentication\\testauthentication' => '/test/TestAuthentication.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\authentication\\user' => '/authentication/User.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\controller\\controller' => '/controller/Controller.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\controller\\inputvalidator' => '/controller/InputValidator.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\controller\\testcontroller' => '/test/TestController.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\model\\course' => '/model/Course.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\model\\courseworker' => '/model/CourseWorker.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\model\\departmentadministrator' => '/model/DepartmentAdministrator.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\model\\evaluation' => '/model/Evaluation.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\model\\instructor' => '/model/Instructor.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\model\\job' => '/model/Job.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\model\\jobapplication' => '/model/JobApplication.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\model\\tamas' => '/model/Tamas.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\model\\testmodel' => '/test/TestModel.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\model\\user' => '/model/User.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\persistence\\persistence' => '/persistence/Persistence.php',
				'ca\\mcgill\\ecse321\\tamas\\web\\persistence\\testpersistence' => '/test/TestPersistence.php'
		);
	}
	$cn = strtolower($class);
	if (isset($classes[$cn])) {
		require dirname(__FILE__) . $classes[$cn];
	}
}
spl_autoload_register('autoload7846c93acdc175fb93142731e3828608');
// @codeCoverageIgnoreEnd
